version: "3.7"

services:

  php:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
    expose:
      - 8080:8080


      
  mariadb:
    image: mariadb:10.4
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'lager'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'rootPW'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootPW'