version: "3.7"

services:

  php:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    expose:
      - 8080:8080


      
  mysql:
    image: mysql
    restart: always
  
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'userAccount'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'springUser'
      # You can use whatever password you like
      MYSQL_PASSWORD: '2!Le0xm29@61cesT'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '85C1aa39.'